# Generated by Django 5.0.4 on 2024-07-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='engine_number',
        ),
    ]
