# Generated by Django 5.0.4 on 2024-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default=1, upload_to='vehicles/'),
            preserve_default=False,
        ),
    ]
